#include "ips.h"
enum ExeMsg
{
	EXE_SVR_INI = 200,
	EXE_SET_IPS,
	EXE_SET_SKT,
	EXE_CLS_SIG,
	EXE_GET_PROCESSOR_SIGNAL,
	EXE_SET_RD,
	EXE_SET_RDSPD,
	EXE_RESET_IPS,
	EXE_PRE_SIG,
	EXE_REOPEN_SIG,
	EXE_YUNTAI_SIG,
	EXE_PLAYBACK_SIG,
};